# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-05 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0003_auto_20180716_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['perioddesc', '-updated']},
        ),
    ]
