# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180606_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cattype',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], default='EX', help_text='Input Expense / Income.', max_length=120),
        ),
    ]
