# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-05 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20180716_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', '-updated']},
        ),
    ]
